steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'RAILS_KEY=$$RAILS_KEY', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/arena-codes', '.']
  secretEnv: ['RAILS_KEY']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/arena-codes']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/arenacodes_master_key/versions/1
    env: 'RAILS_KEY'
