steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'RAILS_MASTER_KEY=$$RAILS_MASTER_KEY', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/arena-codes', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/arena-codes']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/RAILS_MASTER_KEY/versions/1
    env: RAILS_MASTER_KEY
