steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/arena-codes', '.']
  secretEnv: ['RAILS_MASTER_KEY']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/arena-codes']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/arenacodes_master_key/versions/1
    env: 'RAILS_MASTER_KEY'

images: ['gcr.io/${PROJECT_ID}/arena-codes']
