steps:
- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ["-c", "docker build --build-arg RAILS_MASTER_KEY=$$RAILS_MASTER_KEY -t gcr.io/${PROJECT_ID}/arena-codes . "]
  secretEnv: ['RAILS_MASTER_KEY']

- id: 'push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/arena-codes']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/arenacodes_master_key/versions/1
    env: RAILS_MASTER_KEY

images: ['gcr.io/${PROJECT_ID}/arena-codes']
