services:
  app:
    image: ruby:3.1.2
    environment:
      - ARENACODES_DATABASE_PASSWORD
      - ARENACODES_DATABASE_USERNAME
    working_dir: '/app'
    entrypoint: ['bundle', 'exec', 'rails', 'server', '--binding=0.0.0.0', '--port=3000']
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - bundle-cache:/usr/local/bundle
      - ./src:/app
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=${ARENACODES_DATABASE_PASSWORD}
      - POSTGRES_USER=${ARENACODES_DATABASE_USERNAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  bundle-cache:
  db-data:
